## 错误处理

1、默认情况下，当程序发生错误时，程序就会退出（崩溃）

2、所以我们希望，在可能会发生错误的地方，进行错误捕获，保证程序可以继续执行， 

### 基本说明

1. go语言追求简洁优雅，所以go不支持传统的try-catch-finally
2. go中引入了处理方式： defer，panic，recover
3. 这几个异常的使用场景可以这么简单的描述： go中的可以抛出一个panic的异常，然后再defer中通过recover 捕获这个异常，然后正常处理

### 错误处理机制

```go
package main

import "fmt"

func testError() {
	// 使用defer + recover 来捕获和处理异常

	defer func() {
		if err:=recover(); err != nil {
			fmt.Println("err=", err);
			// 处理异常
			fmt.Println("send email")
		}
	}()
	num1 := 100
	num2 := 0
	res := num1 / num2
	fmt.Print("res", res)
}

func main() {
	fmt.Println("error handle")
	testError()
}

```

### 自定义错误

go程序中，支持自定义错误，使用 errors.New  和 panic 内置函数

1. errors.New("错误说明")，会返回一个error类型的错误，表示一个错误
2. panic 内置函数，接受一个interface() 类型的值（也就是任何值）作为参数，**可以接受一个error类型的变量，输出错误信息，并退出程序**

```go
func readConf(name string) (err error) {
	if name == "config.ini" {
		return nil
	} else {
		// 返回一个自定义错误
		return errors.New("读取文件失败")
	}
}

func test02() {
	err := readConf("config.ini")
	if err != nil {
		// 抛出异常，终止程序
		panic(err)
	}
	fmt.Print("test02 done")
}

func main() {
	fmt.Println("error handle")
	test02()
}
```





